services:
  project-db:
    image: postgres:17.2-alpine
    container_name: project-mock-db
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: ace
      POSTGRES_PASSWORD: charitan
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d project -U ace"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5